handlers:
- url: /static/
  static_path: static

- url: /robots.txt
  static_path: static/robots.txt

- url: /favicon.ico
  static_path: static/image/breaking.ico

- url: /google72b20c9b0c5410e5.html
  static_path: static/google72b20c9b0c5410e5.html
